manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/0nOff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main-second
      import: app/west.yml
  self:
    path: config
